#!/bin/bash

TESTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/src/tests"
FILES=`ls $TESTDIR`

for FILE in $FILES
do
	if [ -x $TESTDIR/$FILE ]; then
        echo "$FILE -------------------"
		$TESTDIR/$FILE
        echo "-------------------------"
	fi
done 
